trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'

variables:
- group: Edaena Container Journey

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- bash: |
    echo "secret1 = $(secret1)"
    echo "secret2 = $(secret2)"
    echo "SourceBranchName = $(Build.SourceBranchName)"
    echo "SourceBranch = $(Build.SourceBranch)"
    branch_name_extracted=$(echo "${SourceBranch/refs\/head\// }")
  displayName: Extract branch name

- bash: |
    curl $SCRIPT > script.sh
    chmod +x ./script.sh
    tag_name="hello-spektate-$(Build.SourceBranchName)-$(Build.BuildId)"
    commitId=$(Build.SourceVersion)
    commitId=$(echo "${commitId:0:7}")
    echo "./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p1 $(Build.BuildId) imageTag $tag_name commitId $commitId service $(Build.Repository.Name)"
    ./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p1 $(Build.BuildId) imageTag $tag_name commitId $commitId service $(Build.Repository.Name)
  displayName: Update manifest pipeline details in CJ db
  env:
    SCRIPT: https://raw.githubusercontent.com/samiyaakhtar/spk/686-simply-pipelines/scripts/update_introspection.sh



- task: Docker@2
  inputs:
    containerRegistry: 'hellorings_acr'
    repository: 'ehellospektate'
    command: 'buildAndPush'
    Dockerfile: '**/src/Dockerfile'
    tags: 'hello-spektate-$(Build.SourceBranchName)-$(Build.BuildId)'
  condition: ne(variables['Build.Reason'], 'PullRequest')
